image: ubuntu:latest

variables:
  DOCKER_DRIVER: btrfs

stages:
    - build

before_script:
    # Configure gitlab runner credentials.
    - echo -e "machine 129.125.166.241
        login gitlab-ci-token
        password ${CI_JOB_TOKEN}" > ~/.netrc
    # Transform local submodules into relative paths.
    - sed -i "s/http:\\/\\/129.125.166.241\\//..\\/..\\//g" .gitmodules
    - sed -i "s/git@129.125.166.241:/..\\/..\\//g" .gitmodules
    # Prepare apt-get cache.
    - export APT_CACHE_DIR=`pwd`/.apt-cache && mkdir -pv $APT_CACHE_DIR
    # Install required packages.
    - apt-get update
    - apt-get -y -o dir::cache::archives="$APT_CACHE_DIR" install
        cmake ninja-build build-essential git mingw-w64 binutils-mingw-w64
    # Initialize submodules.
    - git submodule sync
    - git submodule update --init

cache:
    key: "$CI_PROJECT_PATH_SLUG $CI_COMMIT_SHA apt-cache"
    paths:
        - .apt-cache/

build:linux:
    stage: build
    script:
        # Perform build.
        - cd build
        - cmake .. -G Ninja
        - ninja
    cache:
        key: "$CI_PROJECT_PATH_SLUG $CI_COMMIT_SHA linux"
        paths:
            - build/
    cache:
        key: "$CI_PROJECT_PATH_SLUG $CI_COMMIT_SHA apt-cache"
        paths:
            - .apt-cache/

build:windows:
    stage: build
    script:
        # Perform build.
        - cd build
        - CC=x86_64-w64-mingw32-gcc-posix
            CXX=x86_64-w64-mingw32-c++-posix cmake ..
            -G Ninja
            -DBUILD_SHARED_LIBS=OFF
            -DCMAKE_SYSTEM_NAME=Windows
        - ninja
    cache:
        key: "$CI_PROJECT_PATH_SLUG $CI_COMMIT_SHA windows"
        paths:
            - build/
    cache:
        key: "$CI_PROJECT_PATH_SLUG $CI_COMMIT_SHA apt-cache"
        paths:
            - .apt-cache/

test:
    stage: test
    script:
        - cd build
        - ls
        - ninja test
    cache:
        key: "$CI_PROJECT_PATH_SLUG $CI_COMMIT_SHA linux"
        paths:
            - build/
    cache:
        key: "$CI_PROJECT_PATH_SLUG $CI_COMMIT_SHA apt-cache"
        paths:
            - .apt-cache/
