image: ubuntu:latest

variables:
    DOCKER_DRIVER: btrfs

stages:
    - build
    - test

before_script:
    # Configure gitlab runner credentials.
    - echo -e "machine 129.125.166.241
        login gitlab-ci-token
        password ${CI_JOB_TOKEN}" > ~/.netrc
    # Transform local submodules into relative paths.
    - sed -i "s/http:\\/\\/129.125.166.241\\//..\\/..\\//g" .gitmodules
    - sed -i "s/git@129.125.166.241:/..\\/..\\//g" .gitmodules
    # Install required packages.
    - apt-get update
    - apt-get -y install
        cmake ninja-build build-essential git mingw-w64 binutils-mingw-w64 gcc-8
    # Initialize submodules.
    - git submodule sync
    - git submodule update --init

build:linux:
    stage: build
    script:
        # Perform build.
        - echo $CI_PROJECT_PATH_SLUG
        - echo $CI_COMMIT_SHA
        - cd build
        - CXX=gcc++-8 cmake ..
            -G Ninja
        - ninja
    cache:
        key: "$CI_PROJECT_PATH_SLUG $CI_COMMIT_SHA linux"
        paths:
            - build/

build:windows:
    stage: build
    script:
        # Perform build.
        - cd build
        - CC=x86_64-w64-mingw32-gcc-posix
            CXX=x86_64-w64-mingw32-c++-posix cmake ..
            -G Ninja
            -DBUILD_SHARED_LIBS=OFF
            -DCMAKE_SYSTEM_NAME=Windows
        - ninja
    cache:
        key: "$CI_PROJECT_PATH_SLUG $CI_COMMIT_SHA windows"
        paths:
            - build/

test:linux:
    stage: test
    script:
        - echo $CI_PROJECT_PATH_SLUG
        - echo $CI_COMMIT_SHA
        - cd build
        - ninja test
    cache:
        key: "$CI_PROJECT_PATH_SLUG $CI_COMMIT_SHA linux"
        paths:
            - build/
