image: ubuntu:latest

variables:
    DOCKER_DRIVER: btrfs

stages:
    - build
    - test
    - lint

before_script:
    # Configure gitlab runner credentials.
    - echo -e "machine 129.125.166.241
        login gitlab-ci-token
        password ${CI_JOB_TOKEN}" > ~/.netrc
    # Transform local submodules into relative paths.
    - sed -i "s/http:\\/\\/129.125.166.241\\//..\\/..\\//g" .gitmodules
    - sed -i "s/git@129.125.166.241:/..\\/..\\//g" .gitmodules

build:linux:
    stage: build
    script:
        # Install required packages.
        - apt-get update
        - apt-get -y install cmake ninja-build build-essential git gcc-8 g++-8
        - update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 700 --slave /usr/bin/g++ g++ /usr/bin/g++-7
        - update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-8 800 --slave /usr/bin/g++ g++ /usr/bin/g++-8
        # Initialize submodules.
        - git submodule sync
        - git submodule update --init
        # Perform build.
        - cd build
        - cmake .. -G Ninja
        - ninja
    cache:
        key: "$CI_PROJECT_PATH_SLUG $CI_COMMIT_SHA linux"
        paths:
            - build/

test:linux:
    stage: test
    script:
        # Install required packages.
        - apt-get update
        - apt-get -y install ninja-build git
        - update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 700 --slave /usr/bin/g++ g++ /usr/bin/g++-7
        - update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-8 800 --slave /usr/bin/g++ g++ /usr/bin/g++-8
        # Initialize submodules.
        - git submodule sync
        - git submodule update --init
        # Start test
        - cd build
        - ninja test
    cache:
        key: "$CI_PROJECT_PATH_SLUG $CI_COMMIT_SHA linux"
        paths:
            - build/

lint:clang-format:
    stage: lint
    script:
        - apt-get update
        - apt-get -y install clang-format
        - if (clang-format $(find src tests -name "*.[ch]pp") -output-replacements-xml | grep -c "<replacement " >/dev/null); then
            echo "Linter errors found, please run clang-format and try again";
            exit 1;
          fi

lint:cppcheck:
    stage: lint
    script:
        - apt-get update
        - apt-get -y install cppcheck
        - cppcheck --enable=all --quiet src/*.cpp &> cppcheck.txt
        - if [[ $(wc -l < cppcheck.txt) -gt 1 ]]; then
            echo "cppcheck errors found:";
            cat cppcheck.txt;
            exit 1;
          fi

lint:clang-tidy:
    stage: lint
    script:
        - apt-get update
        - apt-get -y install clang-tidy
        - clang-tidy -quiet -checks="-*,bugprone-*,cert-*,clang-analyzer-*,cppcoreguidelines-*,misc-*,modernize-*,mpi-*,performance-*,readability-*,hicpp-*,cert-*,-cppcoreguidelines-pro-type-reinterpret-cast,-cppcoreguidelines-pro-bounds-constant-array-index,-cppcoreguidelines-pro-bounds-pointer-arithmetic,-readability-implicit-bool-conversion,-hicpp-signed-bitwise" -p=build -warnings-as-errors="*" src/*
