image: ubuntu:latest

variables:
    DOCKER_DRIVER: btrfs

stages:
    - build
    - test
    - lint

before_script:
    # Configure gitlab runner credentials.
    - echo -e "machine 129.125.166.241
        login gitlab-ci-token
        password ${CI_JOB_TOKEN}" > ~/.netrc
    # Transform local submodules into relative paths.
    - sed -i "s/http:\\/\\/129.125.166.241\\//..\\/..\\//g" .gitmodules
    - sed -i "s/git@129.125.166.241:/..\\/..\\//g" .gitmodules
    # Install required packages.
    - apt-get update
    - apt-get -y install
        cmake ninja-build build-essential git gcc-8 g++-8 clang-format
    - update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 700 --slave /usr/bin/g++ g++ /usr/bin/g++-7
    - update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-8 800 --slave /usr/bin/g++ g++ /usr/bin/g++-8
    # Initialize submodules.
    - git submodule sync
    - git submodule update --init

build:linux:
    stage: build
    script:
        # Perform build.
        - echo $CI_PROJECT_PATH_SLUG
        - echo $CI_COMMIT_SHA
        - cd build
        - cmake .. -G Ninja
        - ninja
    cache:
        key: "$CI_PROJECT_PATH_SLUG $CI_COMMIT_SHA linux"
        paths:
            - build/

test:linux:
    stage: test
    script:
        - echo $CI_PROJECT_PATH_SLUG
        - echo $CI_COMMIT_SHA
        - cd build
        - ninja test
    cache:
        key: "$CI_PROJECT_PATH_SLUG $CI_COMMIT_SHA linux"
        paths:
            - build/

lint:linux:
    stage: lint
    script:
        - if (clang-format $(find src tests -name "*.[ch]pp") -output-replacements-xml | grep -c "<replacement " >/dev/null); then
            echo "Linter errors found, please run clang-format and try again";
            exit 1;
          fi
